name: trufflehog

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    name: trufflehog
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: HEAD
          extra_args: --only-verified
